
services:
  app:
    image: dev.chat-app:latest
    container_name: dev.chat-app

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "${PORT}:${PORT}"

    restart: unless-stopped